# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-08 18:59
from __future__ import unicode_literals

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20160808_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_video',
            field=embed_video.fields.EmbedVideoField(blank=True, null=True, verbose_name='Видео'),
        ),
    ]
