# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-13 16:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import embed_video.fields
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_auto_20160811_1830'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Имя автора')),
                ('author_image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Фотография автора')),
            ],
            options={
                'verbose_name_plural': 'Авторы',
                'db_table': 'author',
                'verbose_name': 'Автор',
            },
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_title', models.CharField(blank=True, max_length=200, null=True)),
                ('home_text', tinymce.models.HTMLField(blank=True, null=True)),
                ('home_image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Изображения')),
                ('home_video', embed_video.fields.EmbedVideoField(blank=True, null=True, verbose_name='Видео')),
                ('home_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Статические страницы',
                'db_table': 'home',
                'verbose_name': 'Главная страница',
                'ordering': ['home_date'],
            },
        ),
        migrations.AddField(
            model_name='article',
            name='article_text_min',
            field=models.CharField(default=4, max_length=250, verbose_name='Аннотация к статье'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='article_author',
            field=models.ForeignKey(default=1, max_length=150, on_delete=django.db.models.deletion.CASCADE, to='article.Author', verbose_name='Имя автора'),
            preserve_default=False,
        ),
    ]
