# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-16 20:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_auto_20160813_1650'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cloudtegs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Теги')),
            ],
            options={
                'db_table': 'cloudtegs',
            },
        ),
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['article_title'], 'verbose_name': 'Статья', 'verbose_name_plural': 'Статьи'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('tree_id', 'level'), 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='keywords',
            options={'verbose_name': 'Ключевое слово', 'verbose_name_plural': 'Ключевые слова'},
        ),
        migrations.AlterField(
            model_name='article',
            name='keywords',
            field=models.ManyToManyField(related_name='keywords', related_query_name='keyword', to='article.Keywords', verbose_name='Ключевые слова поиска'),
        ),
        migrations.AlterField(
            model_name='keywords',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Кто ищет - тот всегда найдет'),
        ),
        migrations.AddField(
            model_name='article',
            name='cloudtegs',
            field=models.ManyToManyField(related_name='cloudtegs', related_query_name='cloudteg', to='article.Cloudtegs', verbose_name='Ключевые слова'),
        ),
    ]
