# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-16 20:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_auto_20160816_2043'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cloudtegs',
            options={'verbose_name': 'тег', 'verbose_name_plural': 'Облако тегов'},
        ),
    ]
