# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-19 18:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0008_auto_20160816_2051'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['article_title'], 'verbose_name': 'Объект недвижимости', 'verbose_name_plural': 'Объекты недвижимости'},
        ),
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': 'Риелтор', 'verbose_name_plural': 'Риелторы'},
        ),
        migrations.AlterField(
            model_name='article',
            name='article_author',
            field=models.ForeignKey(max_length=150, on_delete=django.db.models.deletion.CASCADE, to='article.Author', verbose_name='Риелтор'),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_text',
            field=tinymce.models.HTMLField(verbose_name='Подробное описание'),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_text_min',
            field=tinymce.models.HTMLField(verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='author',
            name='author_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Фотография риелтора'),
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Риелтор'),
        ),
    ]
