# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-20 18:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0010_auto_20160820_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='phone',
            field=models.CharField(default=2, max_length=20, verbose_name='Телефон'),
            preserve_default=False,
        ),
    ]
